apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: citynex
  namespace: flux-system
spec:
  interval: 30s
  path: ../citynex-api-service
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-apps
  targetNamespace: default