apiVersion: v1
kind: Service
metadata:
  name: citynex-api-service
spec:
  selector:
    app: citynex-api
  ports:
    - protocol: TCP
      port: 80
      nodePort: 32000
      targetPort: 5000
  type: NodePort  # Change to NodePort if using Minikube